# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Be8ZloyxC1pU1YzmrEUuRA2ih0ZxN8ic
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("--- AYLIK BÜTÇE VE HARCAMA ANALİZİ ---")

gelir = float(input("Bu ayki toplam geliriniz (TL): "))

sabit_kategoriler = ['Kira', 'Mutfak', 'Fatura', 'Eğlence', 'Ulaşım', 'Diğer']
harcamalar = []

print("\n--- Harcama Girişi ---")
print("İlgili kategori için harcamanız yoksa '0' yazıp geçebilirsiniz.\n")

for kategori in sabit_kategoriler:
    tutar = float(input(f"'{kategori}' için toplam harcama (TL): "))

    if tutar > 0:
        print(f"  '{kategori}' harcaması ağırlıklı olarak ne zaman yapıldı?")
        print("  1 - Hafta İçi")
        print("  2 - Hafta Sonu")
        secim = input("  Seçiminiz (1 veya 2): ").strip()

        zaman = "Hafta Sonu" if secim == '2' else "Hafta İçi"

        harcamalar.append({
            'Kategori': kategori,
            'Tutar': tutar,
            'Zaman': zaman
        })
        print()

df = pd.DataFrame(harcamalar)

toplam_harcama = df['Tutar'].sum()
kalan_bakiye = gelir - toplam_harcama

en_cok_harcanan_kategori = df.groupby('Kategori')['Tutar'].sum().idxmax()
kategori_max_tutar = df.groupby('Kategori')['Tutar'].sum().max()

zaman_analizi = df.groupby('Zaman')['Tutar'].sum()
en_cok_harcanan_zaman = zaman_analizi.idxmax()
zaman_max_tutar = zaman_analizi.max()

# --- ÖZET ANALİZ RAPORU ---
print("\n" + "="*45)
print("             ANALİZ SONUÇLARI             ")
print("="*45)
print(f"Aylık Gelir           : {gelir:,.2f} TL")
print(f"Toplam Harcama        : {toplam_harcama:,.2f} TL")
print(f"KALAN BAKİYE          : {kalan_bakiye:,.2f} TL")
print("-" * 45)
print(f" En Çok Harcanan Alan   : {en_cok_harcanan_kategori} ({kategori_max_tutar:,.2f} TL)")
print(f" En Çok Harcanan Dönem  : {en_cok_harcanan_zaman} ({zaman_max_tutar:,.2f} TL)")
print("="*45 + "\n")

plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
fig, axes = plt.subplots(1, 2, figsize=(14,6))

renkler = [
    '#FFB7B2',
    '#AEC6CF',
    '#C3B1E1',
    '#B39EB5',
    '#FFDAC1',
    '#E6E6FA'
]

kategori_df = df.groupby('Kategori')['Tutar'].sum()
axes[0].pie(
    kategori_df,
    labels=kategori_df.index,
    autopct='%1.1f%%',
    startangle=90,
    colors=renkler[:len(kategori_df)]
)
axes[0].set_title("Harcamaların Kategorilere Göre Dağılımı (%)", fontsize=12, fontweight='bold')

sns.barplot(
    x=zaman_analizi.index,
    y=zaman_analizi.values,
    hue=zaman_analizi.index,
    ax=axes[1],
    palette=['#AEC6CF', '#FFB7B2'],
    legend=False
)
axes[1].set_title("Hafta İçi vs Hafta Sonu Harcama Karşılaştırması (TL)", fontsize=12, fontweight='bold')
axes[1].set_ylabel("Tutar (TL)")
axes[1].set_xlabel("Dönem")

plt.tight_layout()
plt.show()